version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - "./API:/var/www/html"
      - "/var/www/html/vendor"

  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: Products
      MYSQL_USER: test1
      MYSQL_PASSWORD: test123
    volumes:
      - ./DB:/var/lib/mysql